version: "3.9"

networks:
  rasptank-net: {}

services:
  app:
    build: .
    image: rasptank2:latest
    container_name: rasptank2
    restart: unless-stopped
    privileged: true
    networks:
      - rasptank-net
    devices:
      - /dev/i2c-1:/dev/i2c-1
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - /dev:/dev
      - /sys:/sys:ro
      - /proc/device-tree:/proc/device-tree:ro
      - /sys/firmware/devicetree/base:/sys/firmware/devicetree/base:ro
      - /boot:/boot:ro
      - /run/udev:/run/udev:ro
    environment:
      PCA9685_ADDR: "0x5f"
      BLINKA_FORCECHIP: "BCM2XXX"
      BLINKA_FORCEBOARD: "RASPBERRY_PI_5"
      SERVO_RELAX: "1"
      CAMERA_BACKEND: "auto"

  nginx:
    image: nginx:stable
    container_name: rasptank-proxy
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - rasptank-net
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
